### PR TITLE
boost-1.72.0 coroutines fix

### PR DESCRIPTION
**Pull request by dmorilha-twilio**
applies patch suggested by boost coroutine' s author: https://github.com/boostorg/coroutine/issues/46#issuecomment-567789931

### CODE REVIEW

**Review by berkus — CHANGES_REQUESTED** [review]
Could you please rename commits according to [the guide](https://chris.beams.io/posts/git-commit/)? You can use this repository's history as an example.

**Comment by dmorilha-twilio** [comment]
@berkus, I finally addressed this and "reworded" the commit based on the previous commits to this repository. Please let me know if you agree.

**Comment by berkus** [comment]
5. https://chris.beams.io/posts/git-commit/#imperative

This is not fixed yet.

**Comment by dmorilha-twilio** [comment]
> 1. https://chris.beams.io/posts/git-commit/#imperative
> 
> This is not fixed yet.

done

**Pull request merged**
